version: "3.8"

services:
  gsheets_watcher_service:
    image: gsheets_watcher
    build: .
    command: python3 main.py
    env_file:
      - ./.env
    volumes:
      - ./main.py:/app/main.py
      - ./src:/app/src

  db:
    build:
      context: ./psql
      dockerfile: Dockerfile
    ports:
    - 5431:5432
    env_file:
      - .env.db
    depends_on:
      - gsheets_watcher_service

